package com.equipo.sanmarkfood.restaurante.ui.theme

import androidx.compose.ui.graphics.Color

// Esquema M3 de San Mark Food. Fuente: docs/handoff-diseno-comensal.md (sección 3)
// + roles faltantes generados con la librería Material Color Utilities.
// Los contenedores de estado y los "on" de contenedor son iguales en claro y oscuro.

// ---- Claro ----
val LightPrimary = Color(0xFF8C1D2F)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFF6D9DC)
val LightOnPrimaryContainer = Color(0xFF3B0711)
val LightSecondary = Color(0xFFF2B53A)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFCE7B8)
val LightOnSecondaryContainer = Color(0xFF2E2000)
val LightTertiary = Color(0xFF3E6B3A)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFD6EBCF)
val LightOnTertiaryContainer = Color(0xFF1F3D1C)
val LightError = Color(0xFFB3261E)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFF9DEDC)
val LightOnErrorContainer = Color(0xFF410E0B)
val LightBackground = Color(0xFFF7F0E4)
val LightOnBackground = Color(0xFF1E1B16)
val LightSurface = Color(0xFFF7F0E4)
val LightOnSurface = Color(0xFF1E1B16)
val LightSurfaceVariant = Color(0xFFEEE1CA)
val LightOnSurfaceVariant = Color(0xFF5C5347)
val LightOutline = Color(0xFF8A7E6C)
val LightOutlineVariant = Color(0xFFD9CCB6)
val LightSurfaceDim = Color(0xFFE3D9C7)
val LightSurfaceBright = Color(0xFFFFF8F1)
val LightSurfaceContainerLowest = Color(0xFFFFFBF4)
val LightSurfaceContainerLow = Color(0xFFFDF2E0)
val LightSurfaceContainer = Color(0xFFEFE5D3)
val LightSurfaceContainerHigh = Color(0xFFE6DCCB)
val LightSurfaceContainerHighest = Color(0xFFEBE1CF)
val LightInverseSurface = Color(0xFF353024)
val LightInverseOnSurface = Color(0xFFFAF0DD)
val LightInversePrimary = Color(0xFFFFB3B6)
val LightSurfaceTint = Color(0xFF8C1D2F)
val LightScrim = Color(0xFF000000)

// ---- Oscuro ----
val DarkPrimary = Color(0xFFFFB2B9)
val DarkOnPrimary = Color(0xFF5F1121)
val DarkPrimaryContainer = Color(0xFFF6D9DC)
val DarkOnPrimaryContainer = Color(0xFF3B0711)
val DarkSecondary = Color(0xFFF2B53A)
val DarkOnSecondary = Color(0xFF422D00)
val DarkSecondaryContainer = Color(0xFFFCE7B8)
val DarkOnSecondaryContainer = Color(0xFF2E2000)
val DarkTertiary = Color(0xFFA6D39C)
val DarkOnTertiary = Color(0xFF0B390E)
val DarkTertiaryContainer = Color(0xFFD6EBCF)
val DarkOnTertiaryContainer = Color(0xFF1F3D1C)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFFF9DEDC)
val DarkOnErrorContainer = Color(0xFF410E0B)
val DarkBackground = Color(0xFF17130F)
val DarkOnBackground = Color(0xFFEDE3D3)
val DarkSurface = Color(0xFF17130F)
val DarkOnSurface = Color(0xFFEDE3D3)
val DarkSurfaceVariant = Color(0xFF4E4635)
val DarkOnSurfaceVariant = Color(0xFFCBBFAD)
val DarkOutline = Color(0xFF9C907E)
val DarkOutlineVariant = Color(0xFF4A4238)
val DarkSurfaceDim = Color(0xFF171309)
val DarkSurfaceBright = Color(0xFF3E392C)
val DarkSurfaceContainerLowest = Color(0xFF120E05)
val DarkSurfaceContainerLow = Color(0xFF1F1B10)
val DarkSurfaceContainer = Color(0xFF2B251F)
val DarkSurfaceContainerHigh = Color(0xFF2E2A1E)
val DarkSurfaceContainerHighest = Color(0xFF393428)
val DarkInverseSurface = Color(0xFFEBE1CF)
val DarkInverseOnSurface = Color(0xFF353024)
val DarkInversePrimary = Color(0xFFA93342)
val DarkSurfaceTint = Color(0xFFFFB2B9)
val DarkScrim = Color(0xFF000000)

// ---- Colores extendidos (sin rol M3) ----
val Pizarra = Color(0xFF23332C)
